In [1]:
import numpy as np
import pandas as pd

In [2]:
data = {
    "Name": ["Aman", "Riya", "Karan", "Simran", "Arjun",
             "Neha", "Rahul", "Priya", "Vikas", "Anjali",
             "Rohit", "Sneha", "Varun", "Isha", "Aditya",
             "Kavya", "Manav", "Tanya", "Yash", "Pooja"],

    "Age": [20, 19, 21, 20, 22,
            19, 21, 20, 22, 19,
            21, 20, 22, 19, 21,
            20, 22, 19, 21, 20],

    "Gender": ["M", "F", "M", "F", "M",
               "F", "M", "F", "M", "F",
               "M", "F", "M", "F", "M",
               "F", "M", "F", "M", "F"],

    "Marks": [85, 91, 76, 88, 69,
              95, 72, 89, 64, 93,
              81, 87, 78, 96, 74,
              90, 68, 84, 79, 92],

    "Attendance": [92, 95, 78, 88, 72,
                   96, 80, 91, 68, 94,
                   85, 89, 76, 97, 82,
                   93, 70, 86, 79, 95],

    "Study_Hours": [5.5, 6.2, 3.8, 5.1, 3.2,
                    7.0, 4.0, 5.8, 2.9, 6.5,
                    4.8, 5.3, 4.2, 7.2, 3.9,
                    6.0, 3.5, 5.0, 4.5, 6.8],

    "Department": ["CSE", "IT", "CSE", "ECE", "IT",
                   "CSE", "ECE", "IT", "CSE", "ECE",
                   "CSE", "IT", "ECE", "CSE", "IT",
                   "ECE", "CSE", "IT", "ECE", "CSE"]
}

In [3]:
df = pd.DataFrame(data)

df
df = pd.DataFrame(data)

In [4]:
df.shape

(20, 7)

In [5]:
df.head()

     Name  Age Gender  Marks  Attendance  Study_Hours Department
0    Aman   20      M     85          92          5.5        CSE
1    Riya   19      F     91          95          6.2         IT
2   Karan   21      M     76          78          3.8        CSE
3  Simran   20      F     88          88          5.1        ECE
4   Arjun   22      M     69          72          3.2         IT

In [6]:
df.head(10)

     Name  Age Gender  Marks  Attendance  Study_Hours Department
0    Aman   20      M     85          92          5.5        CSE
1    Riya   19      F     91          95          6.2         IT
2   Karan   21      M     76          78          3.8        CSE
3  Simran   20      F     88          88          5.1        ECE
4   Arjun   22      M     69          72          3.2         IT
5    Neha   19      F     95          96          7.0        CSE
6   Rahul   21      M     72          80          4.0        ECE
7   Priya   20      F     89          91          5.8         IT
8   Vikas   22      M     64          68          2.9        CSE
9  Anjali   19      F     93          94          6.5        ECE

In [7]:
df.tail(3)

     Name  Age Gender  Marks  Attendance  Study_Hours Department
17  Tanya   19      F     84          86          5.0         IT
18   Yash   21      M     79          79          4.5        ECE
19  Pooja   20      F     92          95          6.8        CSE

In [8]:
df.columns

Index(['Name', 'Age', 'Gender', 'Marks', 'Attendance', 'Study_Hours',
       'Department'],
      dtype='object')

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         20 non-null     object
 1   Age          20 non-null     int64
 2   Gender       20 non-null     object
 3   Marks        20 non-null     int64
 4   Attendance   20 non-null     int64
 5   Study_Hours  20 non-null     float64
 6   Department   20 non-null     object
dtypes: float64(1), int64(3), object(3)
memory usage: 1.2+ KB

In [10]:
df.describe()

             Age      Marks  Attendance  Study_Hours
count  20.000000  20.000000   20.000000    20.000000
mean   20.400000  82.550000   85.300000     5.060000
std     1.095445   9.632593    9.182936     1.301174
min    19.000000  64.000000   68.000000     2.900000
25%    19.750000  75.500000   78.750000     3.975000
50%    20.000000  84.500000   87.000000     5.050000
75%    21.000000  90.250000   93.250000     6.050000
max    22.000000  96.000000   97.000000     7.200000

In [13]:
df["Marks"]

0     85
1     91
2     76
3     88
4     69
5     95
6     72
7     89
8     64
9     93
10    81
11    87
12    78
13    96
14    74
15    90
16    68
17    84
18    79
19    92
Name: Marks, dtype: int64

In [14]:
df["Marks"].max()

96

In [15]:
df["Marks"].min()

64

In [16]:
print("Mean:", df["Marks"].mean())
print("Median:", df["Marks"].median())
print("Maximum:", df["Marks"].max())
print("Minimum:", df["Marks"].min())
print("Standard Deviation:", df["Marks"].std())
print("Variance:", df["Marks"].var())
print("Sum:", df["Marks"].sum())

Mean: 82.55
Median: 84.5
Maximum: 96
Minimum: 64
Standard Deviation: 9.632592699022581
Variance: 92.78684210526315
Sum: 1651

In [17]:
marks = df["Marks"].to_numpy()

print(marks)

[85 91 76 88 69 95 72 89 64 93 81 87 78 96 74 90 68 84 79 92]

In [18]:
print(np.mean(marks))
print(np.median(marks))
print(np.max(marks))
print(np.min(marks))
print(np.std(marks))

82.55
84.5
96
64
9.388690004468142

In [19]:
marks = np.array(df["Marks"])

print("Original:", marks)

print("Marks + 5:", marks + 5)

print("Marks * 2:", marks * 2)

print("Marks / 2:", marks / 2)

Original: [85 91 76 88 69 95 72 89 64 93 81 87 78 96 74 90 68 84 79 92]
Marks + 5: [ 90  96  81  93  74 100  77  94  69  98  86  92  83 101  79  95  73  89
  84  97]
Marks * 2: [170 182 152 176 138 190 144 178 128 186 162 174 156 192 148 180 136 168
 158 184]
Marks / 2: [42.5 45.5 38.  44.  34.5 47.5 36.  44.5 32.  46.5 40.5 43.5 39.  48.
 37.  45.  34.  42.  39.5 46. ]

In [26]:
df["Result"] = np.where(df["Marks"] >= 40, "Pass", "Fail")
df

      Name  Age Gender  Marks  Attendance  Study_Hours Department Result
0     Aman   20      M     85          92          5.5        CSE   Pass
1     Riya   19      F     91          95          6.2         IT   Pass
2    Karan   21      M     76          78          3.8        CSE   Pass
3   Simran   20      F     88          88          5.1        ECE   Pass
4    Arjun   22      M     69          72          3.2         IT   Pass
5     Neha   19      F     95          96          7.0        CSE   Pass
6    Rahul   21      M     72          80          4.0        ECE   Pass
7    Priya   20      F     89          91          5.8         IT   Pass
8    Vikas   22      M     64          68          2.9        CSE   Pass
9   Anjali   19      F     93          94          6.5        ECE   Pass
10   Rohit   21      M     81          85          4.8        CSE   Pass
11   Sneha   20      F     87          89          5.3         IT   Pass
12   Varun   22      M     78          76          4.2        ECE   Pass
13    Isha   19      F     96          97          7.2        CSE   Pass
14  Aditya   21      M     74          82          3.9         IT   Pass
15   Kavya   20      F     90          93          6.0        ECE   Pass
16   Manav   22      M     68          70          3.5        CSE   Pass
17   Tanya   19      F     84          86          5.0         IT   Pass
18    Yash   21      M     79          79          4.5        ECE   Pass
19   Pooja   20      F     92          95          6.8        CSE   Pass

In [27]:
np.where(df["Marks"] >= 40, "Pass", "Fail")

array(['Pass', 'Pass', 'Pass', 'Pass', 'Pass', 'Pass', 'Pass', 'Pass',
       'Pass', 'Pass', 'Pass', 'Pass', 'Pass', 'Pass', 'Pass', 'Pass',
       'Pass', 'Pass', 'Pass', 'Pass'], dtype='<U4')

In [30]:
df["Grade"] = np.where(df["Marks"] >= 90, "A+",
                np.where(df["Marks"] >= 80, "A",
                np.where(df["Marks"] >= 70, "B",
                np.where(df["Marks"] >= 60, "C", "D"))))
df[["Name", "Marks", "Grade"]]

      Name  Marks Grade
0     Aman     85     A
1     Riya     91    A+
2    Karan     76     B
3   Simran     88     A
4    Arjun     69     C
5     Neha     95    A+
6    Rahul     72     B
7    Priya     89     A
8    Vikas     64     C
9   Anjali     93    A+
10   Rohit     81     A
11   Sneha     87     A
12   Varun     78     B
13    Isha     96    A+
14  Aditya     74     B
15   Kavya     90    A+
16   Manav     68     C
17   Tanya     84     A
18    Yash     79     B
19   Pooja     92    A+

In [32]:
df[df["Marks"] > 80]

      Name  Age Gender  Marks  Attendance  Study_Hours Department Result Grade
0     Aman   20      M     85          92          5.5        CSE   Pass     A
1     Riya   19      F     91          95          6.2         IT   Pass    A+
3   Simran   20      F     88          88          5.1        ECE   Pass     A
5     Neha   19      F     95          96          7.0        CSE   Pass    A+
7    Priya   20      F     89          91          5.8         IT   Pass     A
9   Anjali   19      F     93          94          6.5        ECE   Pass    A+
10   Rohit   21      M     81          85          4.8        CSE   Pass     A
11   Sneha   20      F     87          89          5.3         IT   Pass     A
13    Isha   19      F     96          97          7.2        CSE   Pass    A+
15   Kavya   20      F     90          93          6.0        ECE   Pass    A+
17   Tanya   19      F     84          86          5.0         IT   Pass     A
19   Pooja   20      F     92          95          6.8        CSE   Pass    A+

In [33]:
df[df["Study_Hours"] > 5]

      Name  Age Gender  Marks  Attendance  Study_Hours Department Result Grade
0     Aman   20      M     85          92          5.5        CSE   Pass     A
1     Riya   19      F     91          95          6.2         IT   Pass    A+
3   Simran   20      F     88          88          5.1        ECE   Pass     A
5     Neha   19      F     95          96          7.0        CSE   Pass    A+
7    Priya   20      F     89          91          5.8         IT   Pass     A
9   Anjali   19      F     93          94          6.5        ECE   Pass    A+
11   Sneha   20      F     87          89          5.3         IT   Pass     A
13    Isha   19      F     96          97          7.2        CSE   Pass    A+
15   Kavya   20      F     90          93          6.0        ECE   Pass    A+
19   Pooja   20      F     92          95          6.8        CSE   Pass    A+

In [34]:
df[(df["Marks"] > 80) & (df["Attendance"] > 90)]

      Name  Age Gender  Marks  Attendance  Study_Hours Department Result Grade
0     Aman   20      M     85          92          5.5        CSE   Pass     A
1     Riya   19      F     91          95          6.2         IT   Pass    A+
5     Neha   19      F     95          96          7.0        CSE   Pass    A+
7    Priya   20      F     89          91          5.8         IT   Pass     A
9   Anjali   19      F     93          94          6.5        ECE   Pass    A+
13    Isha   19      F     96          97          7.2        CSE   Pass    A+
15   Kavya   20      F     90          93          6.0        ECE   Pass    A+
19   Pooja   20      F     92          95          6.8        CSE   Pass    A+

In [35]:
df.sort_values("Marks", ascending=False)

      Name  Age Gender  Marks  Attendance  Study_Hours Department Result Grade
13    Isha   19      F     96          97          7.2        CSE   Pass    A+
5     Neha   19      F     95          96          7.0        CSE   Pass    A+
9   Anjali   19      F     93          94          6.5        ECE   Pass    A+
19   Pooja   20      F     92          95          6.8        CSE   Pass    A+
1     Riya   19      F     91          95          6.2         IT   Pass    A+
15   Kavya   20      F     90          93          6.0        ECE   Pass    A+
7    Priya   20      F     89          91          5.8         IT   Pass     A
3   Simran   20      F     88          88          5.1        ECE   Pass     A
11   Sneha   20      F     87          89          5.3         IT   Pass     A
0     Aman   20      M     85          92          5.5        CSE   Pass     A
17   Tanya   19      F     84          86          5.0         IT   Pass     A
10   Rohit   21      M     81          85          4.8        CSE   Pass     A
18    Yash   21      M     79          79          4.5        ECE   Pass     B
12   Varun   22      M     78          76          4.2        ECE   Pass     B
2    Karan   21      M     76          78          3.8        CSE   Pass     B
14  Aditya   21      M     74          82          3.9         IT   Pass     B
6    Rahul   21      M     72          80          4.0        ECE   Pass     B
4    Arjun   22      M     69          72          3.2         IT   Pass     C
16   Manav   22      M     68          70          3.5        CSE   Pass     C
8    Vikas   22      M     64          68          2.9        CSE   Pass     C

In [36]:
df.loc[df["Marks"].idxmax()]

Name           Isha
Age              19
Gender            F
Marks            96
Attendance       97
Study_Hours     7.2
Department      CSE
Result         Pass
Grade            A+
Name: 13, dtype: object

In [37]:
df[df["Department"] == "CSE"]

     Name  Age Gender  Marks  Attendance  Study_Hours Department Result Grade
0    Aman   20      M     85          92          5.5        CSE   Pass     A
2   Karan   21      M     76          78          3.8        CSE   Pass     B
5    Neha   19      F     95          96          7.0        CSE   Pass    A+
8   Vikas   22      M     64          68          2.9        CSE   Pass     C
10  Rohit   21      M     81          85          4.8        CSE   Pass     A
13   Isha   19      F     96          97          7.2        CSE   Pass    A+
16  Manav   22      M     68          70          3.5        CSE   Pass     C
19  Pooja   20      F     92          95          6.8        CSE   Pass    A+